# Generated by Django 5.0.6 on 2024-06-06 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='students',
            table='tblStudent',
        ),
    ]
